# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirrorful < Formula
  desc ""
  homepage "https://github.com/Mirrorful/mirrorful"
  version "0.1.5"

  on_macos do
    url "https://github.com/Mirrorful/mirrorful/releases/download/v0.1.5/mirrorful_0.1.5_darwin_all.tar.gz"
    sha256 "ed3fd20d5244f7854ef1d8a4c41da14cb5f4912561f4a4cb864ff6f147883206"

    def install
      bin.install "mirrorful"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mirrorful/mirrorful/releases/download/v0.1.5/mirrorful_0.1.5_linux_arm64.tar.gz"
      sha256 "216e1ffcb81a8452c6d1b3f8dfa4a97243a6048242a15ba14f1cca9e7ae475da"

      def install
        bin.install "mirrorful-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Mirrorful/mirrorful/releases/download/v0.1.5/mirrorful_0.1.5_linux_amd64.tar.gz"
      sha256 "ac6809a70d5626157642419494d3b4673fddfed5da74ae2e62baa45aa4d3b6d4"

      def install
        bin.install "mirrorful-cli"
      end
    end
  end
end
