# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirrorful < Formula
  desc ""
  homepage "https://github.com/Mirrorful/mirrorful"
  version "0.1.6"

  on_macos do
    url "https://github.com/Mirrorful/mirrorful/releases/download/v0.1.6/mirrorful_0.1.6_darwin_all.tar.gz"
    sha256 "4bce435f82d2d693cd8ecfe442795bc598d098ad5e48542d4d7d1bb6ea606505"

    def install
      bin.install "mirrorful"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mirrorful/mirrorful/releases/download/v0.1.6/mirrorful_0.1.6_linux_arm64.tar.gz"
      sha256 "79e250067d92aa1236ec828029729104a720d104550c1646044c8e1aec5d14fc"

      def install
        bin.install "mirrorful"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Mirrorful/mirrorful/releases/download/v0.1.6/mirrorful_0.1.6_linux_amd64.tar.gz"
      sha256 "27b3a46d45af6b0ea8bbe465cbf55949815757c6abe6a016788dc03c11818fed"

      def install
        bin.install "mirrorful"
      end
    end
  end
end
